---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: knative-monitoring

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: knative-monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: knative-monitoring

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: knative-monitoring
  labels:
    k8s-app: fluentd
    version: v1
    serving.knative.dev/release: "v0.17.0"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd
        version: v1
        serving.knative.dev/release: "v0.17.0"
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: fluentd
      # automountServiceAccountToken: true
      # tolerations:
      #   - key: node-role.kubernetes.io/master
      #     effect: NoSchedule
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch-logging"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            # Option to configure elasticsearch plugin with self signed certs
            # ================================================================
            - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
              value: "true"
            # Option to configure elasticsearch plugin with tls
            # ================================================================
            - name: FLUENT_ELASTICSEARCH_SSL_VERSION
              value: "TLSv1_2"
            # X-Pack Authentication
            # =====================
            - name: FLUENT_ELASTICSEARCH_USER
              value: "elastic"
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              value: "1z5Z9fGyvm57H7b865Ulmoa1"
            # Logz.io Authentication
            # ======================
            # - name: LOGZIO_TOKEN
            #   value: "ThisIsASuperLongToken"
            # - name: LOGZIO_LOGTYPE
            #   value: "kubernetes"
            - name: KUBERNETES_VERIFY_SSL
              value: "false"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      nodeSelector:
        beta.kubernetes.io/fluentd-ready: "true"
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
