apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-ds
  namespace: knative-monitoring
  labels:
    app: fluentd-ds
    version: v3.0.4
    serving.knative.dev/release: "v0.17.0"
spec:
  selector:
    matchLabels:
      app: fluentd-ds
      version: v3.0.4
  template:
    metadata:
      labels:
        app: fluentd-ds
        version: v3.0.4
        serving.knative.dev/release: "v0.17.0"
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: fluentd-ds
      automountServiceAccountToken: true
      containers:
        - name: fluentd-ds
          # image: quay.io/fluentd_elasticsearch/fluentd:v3.0.4
          image: knativedev/fluentd-elasticsearch:latest
          env:
            - name: FLUENTD_ARGS
              value: --no-supervisor -q
            # - name: KUBERNETES_SERVICE_HOST
            #   value: "172.17.111.57"
            # - name: KUBERNETES_SERVICE_PORT
            #   value: "6443"
            - name: KUBERNETES_VERIFY_SSL
              value: "false"
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlibkubeletpods
              mountPath: /var/lib/kubelet/pods
              readOnly: true
            - name: libsystemddir
              mountPath: /host/lib
              readOnly: true
            - name: config-volume
              mountPath: /etc/fluent/config.d
            # - name: config-conf
            #   mountPath: /etc/fluent
          ports:
            - containerPort: 24231
              name: prometheus
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: prometheus
            initialDelaySeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: prometheus
            initialDelaySeconds: 5
            timeoutSeconds: 10
      nodeSelector:
        beta.kubernetes.io/fluentd-ds-ready: "true"
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - # It is needed because files under /var/log/containers link to /var/log/pods
          name: varlogpods
          hostPath:
            path: /var/log/pods
        - # It is needed because files under /var/log/pods link to /var/lib/docker/containers
          name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - # It is needed because user-container's /var/log is located in /var/lib/kubelet/pods/*/volumes/
          name: varlibkubeletpods
          hostPath:
            path: /var/lib/kubelet/pods
        - # It is needed to copy systemd library to decompress journals
          name: libsystemddir
          hostPath:
            path: /usr/lib64
        - name: config-volume
          configMap:
            name: fluentd-ds-config
        # - name: config-conf
        #   configMap:
        #     name: fluentd-conf
